class SMTP_Template():
    """Template to body of email"""

    def TemplateHTML(self, objNotification: object) -> str:
        """Build body of Email"""        

        return f"""\
            <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
            <html xmlns="http://www.w3.org/1999/xhtml">
                <head>    
                    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
                    <title>SmartTrack Notification</title>
                    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
                </head>
                <body align="center" style="margin: 0; padding: 0;">
                    <table cellpadding="0" cellspacing="0" width="600">
                        <tr class="header">
                            <td align="center" bgcolor="#9eff9e" style="padding: 10px 0; height: 100px; width: 100%; font-size: xx-large; font-weight: bold; font-style: italic;">
                                SmartTrack Information
                            </td>
                        </tr>
                        <tr class="body">
                            <table cellpadding="0" cellspacing="0" width="600">
                                <td td bgcolor="#e8e8e8" style="width: 100%; padding: 10px 40px; font-size: large;">
                                </td>
                                <tr>
                                    <td bgcolor="#e8e8e8" style="width: 100%; padding: 10px 40px; font-size: large;"> Hi, </td>
                                </tr>
                                <tr class="iconMessage">
                                    <td bgcolor="#e8e8e8" align="center" style="width: 100%; padding: 10px 40px; font-size: large;">
                                        <img src="cid:iconMessage" style="display: block; margin: 0 auto;" width="200" height="200">
                                    </td>
                                </tr>
                                <tr class="Notification">
                                    <td bgcolor="#e8e8e8" style="width: 100%; padding: 10px 40px; font-size: large;">
                                        A Notifications has been generated by SmartTrack, see the informations below:
                                    </td>
                                </tr>
                                <tr class="Object">
                                    <td bgcolor="#e8e8e8" style="padding: 20px 20px 20px 20px;">
                                        <table cellpadding="0" cellspacing="0" width="560">
                                            <tr>
                                                <td align="center" bgcolor="#c9c9c9" style="width: 100%; padding: 10px 10px 10px 10px; font-size: large; border-top-left-radius: 20px; border-top-right-radius: 20px;"><strong>Message</strong>: {objNotification["message"]} </td>
                                            </tr>
                                            <tr>
                                                <td align="center" bgcolor="#c9c9c9" style="width: 100%; padding: 10px 10px; font-size: large;"><strong>ID</strong>: {objNotification["object"]["id"]} </td>
                                            </tr>
                                            <tr>
                                                <td align="center" bgcolor="#c9c9c9" style="width: 100%; padding: 10px 10px 10px 10px; font-size: large; border-bottom-left-radius: 20px; border-bottom-right-radius: 20px;"><strong>Type</strong>: {objNotification["object"]["type"]} </td>
                                            </tr>
                                        </table>
                                    </td>                        
                                </tr>
                                <tr class="Site">
                                    <td bgcolor="#e8e8e8" style="width: 100%; padding: 20px 40px 20px 40px; font-size: large;">
                                        For more informations, please access: <a href="">SmartTrack</a>.
                                    </td>                       
                                </tr>
                            </table>
                        </tr>
                        <tr class="foot">
                            <td bgcolor="#9eff9e">                   
                                <table cellpadding="0" cellspacing="0" width="600">
                                    <tr>
                                        <td class="Logo" align="center" bgcolor="#9eff9e" style="display: block; padding: 10px;">
                                            <img class="iconLogo" src="cid:iconLogo" width="100" height="100">
                                        </td>
                                        <td class="Contact" bgcolor="#9eff9e" style="display: block; padding: 10px;">
                                            <table cellpadding="0" cellspacing="0" width="100%">
                                                <tr>
                                                    <td align="center" style="width: 100%; padding: 5px; font-size: larger;"><strong>SmartTrack LTDA.</strong></td>                                        
                                                </tr>
                                                <tr>
                                                    <td align="center" style="width: 100%; padding: 5px; font-size: larger;"><strong>Email: <a href="mailto:smarttrack.notifications@gmail.com">SmartTrack.Notifications@gmail.com</a></strong></td>
                                                </tr>                            
                                                <tr>
                                                    <td align="center" style="width: 100%; padding: 5px; font-size: larger;"><strong>Site:  <a href="">http://www.SmartTrack.com.br</a></strong></td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>
                </body>
            </html>
        """

