openapi: 3.0.0
tags:
  - name: Notifications
get:  
  description: Get all Notifications on DB
responses:
    '200':
      description: Successful response
    '400':
      description: Bad Request
    '500':
      description: Internal Server Error