openapi: 3.0.0
tags:
  - name: Notifications
post:  
  description: Create a new notification on DB and send email to notify 
  parameters:
  - name: message
    in: body
    description: The message to describe the notification
    type: string
  - name: email
    in: body    
    description: The emails to send the notification
    required: true
    type: array
    items:
      type: string
  - name: datetime
    in: body
    type: string
    description: The current time that notifications was trigged
  - name: object
    in: body
    type: object
    description: The current object trigged

definitions:
  Error:
    type: object    
    properties:
      Error:
        type: array
        items:
          type: string
          example: 'Error message'

responses:
    '200':
      description: Successful response      
    '400':
      description: Bad Request
      schema:
        $ref: '#/definitions/Error'
    '500':
      description: Internal Server Error


